name: Metamorphosis
version: '0.1.0.1'
synopsis: Transform data types using Template Haskell
author: Maxime Bourget
maintainer: bmx007@gmail.com
license: BSD3
extra-source-files:
- ChangeLog.md
dependencies:
- base >=4.8 && <5.0
- template-haskell >= 2.18.0.0 && <3.0
- containers >= 0.5 && < 0.6
- microlens
- microlens-th
library:
  source-dirs: src

tests:
  spec:
    main : Spec.hs
    source-dirs:
      - test

    dependencies:
      - Metamorphosis
      - hspec >= 2.1.8
      - doctest
      - lens
